### ISSUE TITLE
"connection error: Unexpected connection close." while trying to make new connection with the peer

### ISSUE THREAD

**Issue by itarataiko** [ls1intum/sReto#1]
Hi Stephan
I'm trying to make new connection between two peer in the sRetoExample application and receiving connection error.
Bellow is the log from two devices.
log from first simulator:
Started browsing using <sReto.BonjourBrowser: 0x78fa7120>
Started advertisement using <sReto.BonjourAdvertiser: 0x78fab800>
Reto[Info] 2015-12-24 13:19:29 +0000: connecting with address data: <1002e35c c0a8006b 00000000 00000000>, port: 58204

Reto[Info] 2015-12-24 13:19:29 +0000:  -- Peer Discovery Information -- 
Reto[Info] 2015-12-24 13:19:29 +0000:  - Peers now reachable: 
Reto[Info]: 	UUID(uuid: [119, 176, 251, 226, 164, 74, 69, 35, 181, 26, 85, 145, 94, 221, 17, 70]) (via UUID(uuid: [119, 176, 251, 226, 164, 74, 69, 35, 181, 26, 85, 145, 94, 221, 17, 70]), cost: 10.0)
Reto[Info] 2015-12-24 13:19:29 +0000:  - No nodes became unreachable.
Reto[Info]:  - No routes changed.

Reto[Info] 2015-12-24 13:19:46 +0000: connecting with address data: <1002e35c c0a8006b 00000000 00000000>, port: 58204
Reto[Info] 2015-12-24 13:19:47 +0000: connecting with address data: <1002e35c c0a8006b 00000000 00000000>, port: 58204
Reto[Info] 2015-12-24 13:19:48 +0000: connecting with address data: <1002e35c c0a8006b 00000000 00000000>, port: 58204
Reto[Info] 2015-12-24 13:19:49 +0000: connecting with address data: <1002e35c c0a8006b 00000000 00000000>, port: 58204
Reto[Info] 2015-12-24 13:19:51 +0000: connecting with address data: <1002e35c c0a8006b 00000000 00000000>, port: 58204
connection error: Unexpected connection close.

Reto[Info] 2015-12-24 13:20:20 +0000:  -- Peer Discovery Information -- 
 - No new nodes reachable.
Reto[Info] 2015-12-24 13:20:20 +0000: Reto[Info]:  - Peers now unreachable: 
Reto[Info] 2015-12-24 13:20:20 +0000: Reto[Info]: 	UUID(uuid: [119, 176, 251, 226, 164, 74, 69, 35, 181, 26, 85, 145, 94, 221, 17, 70]))
removing: <sReto.RemotePeer: 0x7a07de60>, existing: <sReto.RemotePeer: 0x7a07de60>
Reto[Info]:  - No routes changed.

Reto[Info] 2015-12-24 13:20:25 +0000: connecting with address data: <1002e363 c0a8006b 00000000 00000000>, port: 58211

Reto[Info] 2015-12-24 13:20:25 +0000:  -- Peer Discovery Information -- 
Reto[Info] 2015-12-24 13:20:25 +0000:  - Peers now reachable: 
Reto[Info]: 	UUID(uuid: [108, 207, 49, 81, 184, 163, 73, 8, 147, 40, 167, 126, 74, 189, 42, 191]) (via UUID(uuid: [108, 207, 49, 81, 184, 163, 73, 8, 147, 40, 167, 126, 74, 189, 42, 191]), cost: 10.0)
Reto[Info] 2015-12-24 13:20:25 +0000:  - No nodes became unreachable.
Reto[Info]:  - No routes changed.

connection error: Unexpected connection close.
Reto[Info] 2015-12-24 13:20:36 +0000: connecting with address data: <1002e363 c0a8006b 00000000 00000000>, port: 58211
Reto[Info] 2015-12-24 13:20:37 +0000: connecting with address data: <1002e363 c0a8006b 00000000 00000000>, port: 58211
Reto[Info] 2015-12-24 13:20:39 +0000: connecting with address data: <1002e363 c0a8006b 00000000 00000000>, port: 58211
Reto[Info] 2015-12-24 13:20:40 +0000: connecting with address data: <1002e363 c0a8006b 00000000 00000000>, port: 58211
Reto[Info] 2015-12-24 13:20:41 +0000: connecting with address data: <1002e363 c0a8006b 00000000 00000000>, port: 58211
connection error: Unexpected connection close.

and second second simulator:

Started browsing using <sReto.BonjourBrowser: 0x7d0380b0>
Reto[Info] 2015-12-24 13:20:23 +0000:  -- Peer Discovery Information -- 
Reto[Info] 2015-12-24 13:20:23 +0000:  - Peers now reachable: 
Reto[Info]: 	UUID(uuid: [194, 68, 33, 217, 74, 39, 66, 183, 156, 114, 211, 139, 192, 66, 172, 216]) (via UUID(uuid: [194, 68, 33, 217, 74, 39, 66, 183, 156, 114, 211, 139, 192, 66, 172, 216]), cost: 10.0)
Reto[Info] 2015-12-24 13:20:23 +0000:  - No nodes became unreachable.
Reto[Info]:  - No routes changed.

Started advertisement using <sReto.BonjourAdvertiser: 0x7d0399a0>
Reto[Info] 2015-12-24 13:20:42 +0000: connecting with address data: <1002e221 c0a80066 00000000 00000000>, port: 57889
Reto[Info] 2015-12-24 13:20:43 +0000: connecting with address data: <1002e221 c0a80066 00000000 00000000>, port: 57889
Reto[Info] 2015-12-24 13:20:44 +0000: connecting with address data: <1002e221 c0a80066 00000000 00000000>, port: 57889
Reto[Info] 2015-12-24 13:20:45 +0000: connecting with address data: <1002e221 c0a80066 00000000 00000000>, port: 57889
Reto[Info] 2015-12-24 13:20:46 +0000: connecting with address data: <1002e221 c0a80066 00000000 00000000>, port: 57889
connection error: Unexpected connection close.

**Comment by krusche** [comment]
Should be fixed with the new version 1.3.0
