### ISSUE TITLE
Crash in Xcode 10

### ISSUE THREAD

**Issue by aslam-unikove** [ls1intum/sReto#12]
Getting crash in Xcode 10 on the following line:
let localPeer = LocalPeer(modules: [wlanModule], dispatchQueue: DispatchQueue.main)
The reason is hashvalue is different in xcode 9 and xcode 10:
public var hashValue: Int {
        return uuid.map { $0.hashValue }.enumerated().reduce(0,
            {
                let (index, hash) = $1
                return $0 ^ (hash << index * 2)
            }
        )
    }

**Comment by Ghostfly** [comment]
+1

**Comment by swainwri** [comment]
Would this work?

public var hashValue: Int {
        return uuid.map { $0.hashValue }.enumerated().reduce(0,
            {
                let (index, hash) = $1
            //return $0 ^ (hash << index * 2)
                                                                
                var hasher = Hasher()
                hasher.combine(index)
                hasher.combine(hash)
                return hasher.finalize()
            }
        )
    }

**Comment by aslam-unikove** [comment]
Working fine now
